spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/mini_project
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: investment-service
server:
  port: '9095'
resilience4j:
  circuitbreaker:
    instances:
      walletService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      walletServiceRetry:
        max-attempts: 3
        wait-duration: 200ms
        retry-exceptions:
          - org.springframework.web.client.RestClientException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - java.lang.IllegalStateException


